services:
  db:
    image: postgres:18.2
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    volumes:
        # - ./data:/var/lib/postgresql/data
        - ./pginit.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      v0:
        ipv4_address: "${POSTGRES_HOST}"
    ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  xampp:
    build: .
    image: xampp
    volumes:
      - ./${ACTIVE_PROJECT}:/${XAMPP_DEPLOYMENT_DIR}
      - ./lampp/etc/php.ini:/opt/lampp/etc/php.ini
      - ./lampp/apache2/conf/httpd.conf:/opt/lampp/apache2/conf/httpd.conf
    networks:
      v0:
        ipv4_address: 10.0.55.10
    ports:
      - 8080:80
      - 8022:22
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
networks:
  v0:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.55.0/24
